Suggested changes to RAP pages on the analysts guide
dfe-analytical-services/analysts-guide pull request #2
Opened 2023-10-04 14:34 UTC by jen-machin

## Overview of changes
I added some extra details and fixed some typos (sorry) on all 4 pages. 

On the **RAP for Statistics page** I have quite a few suggested changes but I didn't want to make these without running them by someone first. They are:
- I think this page should come first in the list of RAP pages as it's a good overview
- I don't know whether it's maybe worth adding a table of contents linking to each of the RAP principles, but this might be too long/unwieldy given how many of them there are. Might be useful for people looking for a specific section though. 
- The diagram under "Where do we need to focus" is too small and difficult to read, and you can't expand it/zoom in. The same is true for the diagrams under "Version controlled final code scripts". 
- "How to get started" only refers to publications, do we need more generic info for non-publication related RAP?
- Some of the code snippets on the page show up ok but are difficult to differentiate from the other text despite the change in font, and other code snippets (like the ones under the "Tidying and processing data in R", "Recyclable code for future use", and "Build capability with in the team" sections) are pretty much impossible to read because of the font colours against the dark background. Could we maybe put code snippets inside boxes with a different colour background or something? 
- Under "Version controlled final code scripts", do we need to more clearly differentiate between the use case for DevOps (private) and GitHub (open source)? It's implied but not sure how clear it'd be to people that are new to using both. 

I maybe should have added these as comments on the actual bits of Markdown text. I can go back and do that if it's better 😄 

Also I asked to merge this to main because there's no development branch that I can see - sorry!

2023-10-04 15:39 UTC, cjrace requested changes
A few minor suggestions though generally this is excellent! 

In general, very happy for you to just make the changes to the stats RAP page.

The diagram on where we need to focus is probably long out of date now, so happy for you to drop it and we can always ditch that part or update to a new place where we want to focus.

For the code snippets I think we can fix those with a custom css script, Rich and Tess had brief goes without quick success but sure with a bit of time we could add that in and overwrite the defaults we have now to improve contrast

2023-10-04 15:39 UTC, cjrace commented on RAP/rap-faq.qmd
> +This means that you should have one 'centralized' script that details all of the different scripts in your repository. This single run script then provides a single reference point for where all of y
should this be 'a fantastic piece of documentation?

2023-10-04 15:39 UTC, cjrace commented on RAP/rap-faq.qmd
> +We run a regular RAP Knowledge Share series in which we share good practice and examples of work. We record each session so that you can refer back to them at a later date if you want to. Previous re
Could the link text be something like 'RAP knowledge share sharepoint folder' or something? Just thinking out of context sharepoint might not make sense / or easily clash if we put other links to sharepoint also on this page

2023-10-04 15:39 UTC, cjrace commented on RAP/rap-statistics.qmd
> +The first place to start for your teams RAP is to store the raw data you use to create underlying data in a Microsoft SQL Server database. This is similar to a Sharepoint area or a shared folder, but
Never occurred to me this should be capitalised - great spot!

2023-10-05 07:48 UTC, jen-machin commented on RAP/rap-expectations.qmd
> +We expect any analyst working in statistics production to know and be able to implement RAP principles, using the recommended tools to meet at least good and great practice. You can see examples of g
I might just drop out the "in statistics production" bit and then it's more applicable to everyone

2023-10-05 10:32 UTC, jen-machin commented
> A few minor suggestions though generally this is excellent!
> 
> In general, very happy for you to just make the changes to the stats RAP page.
> 
> The diagram on where we need to focus is probably long out of date now, so happy for you to drop it and we can always ditch that part or update to a new place where we want to focus.
> 
> For the code snippets I think we can fix those with a custom css script, Rich and Tess had brief goes without quick success but sure with a bit of time we could add that in and overwrite the defaults we have now to improve contrast.
> 
> For the ordering, I'm happy for you to change that about I think it makes sense.
> 
> Not sure on the table, as I guess the table of contents on the right should give that? Though we can certainly have a look at it and if there's a way we can make it easier to navigate.

I think I've made all of these changes now 😄 I chose a theme for the code snippets (sadly not Dracula) but happy to change this to a different one if people have a preference. There's info on the different themes [here](https://quarto.org/docs/output-formats/html-code.html#highlighting). Also some of the code blocks were specified as R code and the others weren't - the theming only works on code blocks that are specifically identified as a certain language so I just modified all the blocks to be R blocks. I don't think this has caused any catastrophes but maybe worth checking.

2023-10-05 11:48 UTC, cjrace submitted a review, later dismissed
Happy to approve - we should take note of this anywhere else we have code chunks to fix the highlighting.

Could you add something to the contributing file about this @jen-machin, just a short sentence or two on how to add in code chunks so the highlighting works for both light and dark matching the theme you've added? Can either be on this branch / PR or in a follow up one

2023-10-05 14:39 UTC, cjrace requested changes

2023-10-05 14:39 UTC, cjrace commented on CONTRIBUTING.md
> +---
Not sure this has worked? 
![image](https://github.com/dfe-analytical-services/analysts-guide/assets/52536248/1cfbd87f-80cc-4890-9910-101a84a08ff3)

I previewed it by switching to the branch then selecting the file, leading me to https://github.com/dfe-analytical-services/analysts-guide/blob/rap-page-additions/CONTRIBUTING.md

2023-10-05 14:39 UTC, cjrace commented on CONTRIBUTING.md
> +resource for the whole analytical community in DfE :sparkles:.
Did you tidy these line lengths manually or was there a package you used to do it?

2023-10-05 14:39 UTC, cjrace commented on CONTRIBUTING.md
>  -->
This is now showing the comment in the preview of the file, was this intentional? 

![image](https://github.com/dfe-analytical-services/analysts-guide/assets/52536248/55a41d5d-ffca-494c-8b22-63b36d6b7d48)

2023-10-05 14:39 UTC, cjrace commented on CONTRIBUTING.md
> +### Pull Request {#pull-request}
Was this intentionally added?

![image](https://github.com/dfe-analytical-services/analysts-guide/assets/52536248/c9e2762b-2ec7-4fd5-8f6b-acd37b4b3dff)

2023-10-05 14:39 UTC, cjrace commented on CONTRIBUTING.md
> +We may ask questions or request additional information. - We may ask for
Think the bullet points have been lost here? 

Preview of this:
![image](https://github.com/dfe-analytical-services/analysts-guide/assets/52536248/8b43e3ed-dbb6-4165-a846-24d50eaf1587)

What it looks like on main (https://github.com/dfe-analytical-services/analysts-guide/blob/main/CONTRIBUTING.md)

![image](https://github.com/dfe-analytical-services/analysts-guide/assets/52536248/1dd21240-38a7-4b1c-b9b9-6293efa1423f)

2023-10-05 14:39 UTC, cjrace commented on CONTRIBUTING.md
> +duplicated - When adding images, save them in the /images folder - When
Think we've lost the bullet point formatting, was this intentional? ([your branch](https://github.com/dfe-analytical-services/analysts-guide/blob/rap-page-additions/CONTRIBUTING.md) is on the left and the [main branch preview](https://github.com/dfe-analytical-services/analysts-guide/blob/main/CONTRIBUTING.md) is on the right in the screenshot below)

![image](https://github.com/dfe-analytical-services/analysts-guide/assets/52536248/b43c9a01-372c-4bcb-9377-5c1ffdd1b073)

2023-10-06 12:44 UTC, cjrace commented
Closing in favour of https://github.com/dfe-analytical-services/analysts-guide/pull/4

2023-10-06 12:44 UTC, closed without merging