Added establishment types reference data
dfe-analytical-services/analysts-guide pull request #49
Opened 2024-04-16 16:20 UTC by rmbielby

## Overview of changes

Similar to the SEN data guidance update, this presents the first iteration of standardisation of the school type fields as reviewed by the data harmonisation champions.

## Why are these changes being made?

These are part of the ongoing effort to establish standardised data guidance for publication teams to follow.

## Detailed description of changes

Standard field names and items are outlined for:

Establishment type group
Establishment governance
Education phase
Establishment type
Provider type

## Checklist before requesting a review
- [ ] I have checked the contributing guidelines
- [ ] I have checked for and linked any relevant issues that this may resolve
- [ ] I have checked that these changes build locally
- [ ] I understand that if merged into main, these changes will be publicly available

2024-04-19 13:03 UTC, cjrace commented on statistics-production/ud.qmd
> +| -------- | --------------------- | ----------- |
Same comment for this table

2024-04-19 13:03 UTC, cjrace commented on statistics-production/ud.qmd
> +| -------- | --------------------- | ----------- | ------------------ |
And same comment for this table too

2024-04-19 14:34 UTC, rmbielby commented on statistics-production/ud.qmd
> +| col_name | Breakdown topic entry | Filter item |
Ok, given that switch a go

2024-04-19 15:11 UTC, cjrace requested changes
Like this now I think that's much cleaner to understand at a glance, one minor point about in page links then will be happy to approve

2024-04-19 15:11 UTC, cjrace commented on statistics-production/ud.qmd
> +If needed, these items can also be reported in the standard **breakdown** field, using a **breakdown_topic** of Establishment type group.
Do we have a section of guidance on this to link to higher up the page?

2024-04-19 15:11 UTC, cjrace commented on statistics-production/ud.qmd
> +If needed, these items can also be reported in the standard **breakdown** field, using a **breakdown_topic** of Establishment governance.
Do we have a section of guidance on this to link to higher up the page?

2024-04-19 16:27 UTC, cjrace commented on statistics-production/ud.qmd
> +Education phase should be listed under he column name **education_phase** where given as a standalone filter or Education phase if included in the **breakdown_topic** / **breakdown** combination. Whe
he typo!

2024-04-22 10:33 UTC, cjrace approved these changes

2024-04-22 13:32 UTC, merged